### PR TITLE
Minimal set of necessary steps

### PR DESCRIPTION
**Pull request by laughedelic**
Working on the steps for #22 here. These are just from the top of my head:

- [x] `get` property
- [x] graph `query`
- [x] edge `source`/`target`
- [x] `inE`/`outE` (as vertex-centric queries)
- [x] `map`/`flatten`/`flatMap`
- [x] `inV`/`outV` as native steps
- [x] `fork` (△), `forkMap`
- [x] `merge` (kind of ▽)

what else is needed?

Related: https://github.com/ohnosequences/puntos-y-flechicas/issues/28

### CODE REVIEW

**Comment by eparejatobes** [comment]
About merge, I just don't understand what kind of behavior you're after. What is this merge supposed to satisfy?

**Comment by laughedelic** [comment]
@eparejatobes this:
```
F[X]
  ⊗   → (F+S)[T]
S[T]
```

where `Container[Inside]` is a notation for a graph type

**Comment by eparejatobes** [comment]
X?

**Comment by laughedelic** [comment]
T

**Comment by eparejatobes** [comment]
OK I see. Why not first convert then merge?

**Comment by laughedelic** [comment]
What is convert?

**Comment by eparejatobes** [comment]
Go from `F[T]` to `(F+S)[T]`, from `S[T]` to `(F+S)[T]`, then merge `(F+S)[T] ⊗ (F+S)[T]` to `(F+S)[T]`

**Comment by laughedelic** [comment]
How is it easier? For this you need the notion of `F+S` container

**Pull request merged**
