### PR TITLE
Par/Or

### PR DESCRIPTION
**Pull request by laughedelic**
Not the highest priority, but anyway would be nice to have it in some simple form in the new version: `⨂/⨁`

### CODE REVIEW

**Comment by eparejatobes** [comment]
One thing missing here is units for both ⊗ and ⊕

**Comment by laughedelic** [comment]
Ahem, what for? :stuck_out_tongue:

**Comment by eparejatobes** [comment]
@laughedelic check 93d0dfc

**Comment by laughedelic** [comment]
Ok, don't mind my last comment. I've taken a look at 93d0dfc1262e90457ad133f57ebf0245d353476e (it just seemed too big at first). So why this way?

**Comment by eparejatobes** [comment]
@laughedelic yes I should have done the docs stuff in a separate commit. This way you'll get better `Inside` inference for constructed instances.

**Comment by eparejatobes** [comment]
In general I've experienced that `this.type` should only be used in a non-abstract context.

**Comment by laughedelic** [comment]
If you say so..

**Comment by laughedelic** [comment]
I'm merging this

**Pull request merged**
